# Generated by Django 3.1.2 on 2020-11-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('userID', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=12)),
                ('type_of_lab', models.CharField(max_length=10)),
                ('room_no', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=15)),
            ],
        ),
    ]
